Strengthen the checking for deploymentAvailable and rolledPodsAreRead…
kuberhealthy/kuberhealthy pull request #1084
Opened 2022-09-29 10:41 UTC by Hungrylion2019

1. rolledPodsAreReady
-  add the UpdatedReplicas and UnavailableReplicas judge to be sure that we update deployement ok

2. deployment
- we set maxUnavailable: 2；if some other pod is not good，it will still think the deployment is ok
- I think it's not enough to be sure the deployment is healthy when some pods occured to error

Signed-off-by: zhicheng.li <zhicheng.li@trip.com>

2022-09-29 11:41 UTC, Hungrylion2019 commented
@integrii

2022-10-15 03:22 UTC, integrii requested changes
Hey @Hungrylion2019 !  It's been a long time since I have seen your code.  This should be fine to do.  I just have a couple small syntax suggestions for you to look at...

2022-10-15 03:22 UTC, integrii commented on cmd/deployment-check/deployment.go
> +				log.Infoln("The ", deployment.Status.AvailableReplicas, " pods of the deployment  are ready and available")
```suggestion
				log.Infoln(deployment.Status.AvailableReplicas, "deployment pods are ready and available.")
```

2022-10-15 03:22 UTC, integrii commented on cmd/deployment-check/deployment.go
> +	return d.Status.Replicas == int32(checkDeploymentReplicas) && d.Status.UpdatedReplicas == int32(checkDeploymentReplicas) && d.Status.AvailableReplicas == int32(checkDeploymentReplicas) && d.Status.R
```suggestion
	return d.Status.Replicas == int32(checkDeploymentReplicas) &&
	d.Status.UpdatedReplicas == int32(checkDeploymentReplicas) &&
	d.Status.AvailableReplicas == int32(checkDeploymentReplicas) &&
	d.Status.ReadyReplicas == int32(checkDeploymentReplicas) &&
	d.Status.UnavailableReplicas < 1 &&
	d.Status.ObservedGeneration > 1
```

2022-10-15 03:22 UTC, integrii commented on cmd/deployment-check/deployment.go
> +		d.Status.ObservedGeneration > 1
```suggestion
```

2022-10-15 03:22 UTC, integrii commented on cmd/deployment-check/deployment.go
> +			if deployment.Status.Replicas == int32(checkDeploymentReplicas) && deployment.Status.AvailableReplicas == int32(checkDeploymentReplicas) && deployment.Status.ReadyReplicas == int32(checkDeployment
```suggestion
			if deployment.Status.Replicas == int32(checkDeploymentReplicas) &&
			deployment.Status.AvailableReplicas == int32(checkDeploymentReplicas) &&
			deployment.Status.ReadyReplicas == int32(checkDeploymentReplicas) &&
			deployment.Status.ObservedGeneration == 1 {
```

2022-10-17 03:41 UTC, Hungrylion2019 commented
> Hey @Hungrylion2019 ! It's been a long time since I have seen your code. This should be fine to do. I just have a couple small syntax suggestions for you to look at...
- Firstly,tks for your review.
- Actually, I have many changes for the kuberhealthy code. But the project has landed and completed, then I'm working for a new projetct aboutt node automatically upgraded、online、offline、switching. 
- I will try my best to update the code from local to remote, and some codes maybe be committed In the name of the company [ctripcloud](https://github.com/ctripcloud)

2022-10-17 16:13 UTC, integrii commented
@Hungrylion2019 there were build fixes in master.  Can you merge the latest master and push it to your branch please?  That should make builds pass on this branch...

2022-10-18 02:36 UTC, Hungrylion2019 commented
@integrii  pls merge this PR，it  just pass the test after I add the signature about your review suggestions.
By the way, I still can't push the code into  the repository without fork mode.

2022-10-19 18:01 UTC, merged